# ABSL
# CARES
# Protobuf
# RE2
# SSL
# ZLIB

if(PROJECT_PREBUILT_PLATFORM_NAME STREQUAL PROJECT_PREBUILT_HOST_PLATFORM_NAME)
  set(gRPC_BUILD_CODEGEN ON)
  set(gRPC_CMAKE_CROSSCOMPILING OFF)
else()
  set(gRPC_BUILD_CODEGEN OFF)
  set(gRPC_CMAKE_CROSSCOMPILING ON)
endif()

set(gRPC_MSVC_CONFIGURE ${CMAKE_BUILD_TYPE})

include("${CMAKE_CURRENT_LIST_DIR}/abseil-cpp.cmake")
include("${CMAKE_CURRENT_LIST_DIR}/c-ares.cmake")
include("${CMAKE_CURRENT_LIST_DIR}/re2.cmake")
# include ("${CMAKE_CURRENT_LIST_DIR}/upb.cmake")

include("${CMAKE_CURRENT_LIST_DIR}/grpc.cmake")
