#!/bin/bash

BACKUP_ASM="$ASM"
BACKUP_CC="$CC"
BACKUP_CXX="$CXX"
BACKUP_SDKROOT="$SDKROOT" # Darwin
BACKUP_DEVROOT="$DEVROOT"
BACKUP_CROSS_SDK="$CROSS_TOP" # openssl
BACKUP_CROSS_SDK="$CROSS_SDK" # openssl
BACKUP_CMAKE_OSX_SYSROOT="$CMAKE_OSX_SYSROOT"
BACKUP_CMAKE_OSX_ARCHITECTURES="$CMAKE_OSX_ARCHITECTURES"
BACKUP_SYSROOT_DIR="$SYSROOT_DIR" # CrayLinux
BACKUP_LOCALBASE="$LOCALBASE" # OpenBSD

unset ASM
unset CC
unset CXX
unset SDKROOT
unset DEVROOT
unset CROSS_TOP
unset CROSS_SDK
unset CMAKE_OSX_SYSROOT
unset CMAKE_OSX_ARCHITECTURES
unset SYSROOT_DIR
unset LOCALBASE
