foreach(TOOLCHAIN_FILE ${ATFRAMEWORK_CHAINLOAD_TOOLCHAIN_FILE})
  include("${TOOLCHAIN_FILE}")
endforeach()

if(CMAKE_VERSION VERSION_GREATER_EQUAL "3.24")
  list(APPEND CMAKE_PROJECT_TOP_LEVEL_INCLUDES "${CMAKE_CURRENT_LIST_DIR}/Import.cmake")
else()
  list(APPEND CMAKE_PROJECT_INCLUDE "${CMAKE_CURRENT_LIST_DIR}/Import.cmake")
endif()
