if(CMAKE_VERSION VERSION_GREATER_EQUAL "3.10")
  include_guard(GLOBAL)
endif()

# =========== third party jemalloc ==================
if(NOT MSVC
   AND NOT MINGW
   AND (NOT ATFRAMEWORK_CMAKE_TOOLSET_THIRD_PARTY_JEMALLOC_INC_DIR
        OR NOT ATFRAMEWORK_CMAKE_TOOLSET_THIRD_PARTY_JEMALLOC_LIB_DIR))
  set(ATFRAMEWORK_CMAKE_TOOLSET_THIRD_PARTY_JEMALLOC_PKG_VERSION 5.2.1)
  set(ATFRAMEWORK_CMAKE_TOOLSET_THIRD_PARTY_JEMALLOC_MODE "release")

  # if ("${CMAKE_BUILD_TYPE}" STREQUAL "Debug") set
  # (ATFRAMEWORK_CMAKE_TOOLSET_THIRD_PARTY_JEMALLOC_MODE "debug") endif()

  set(ATFRAMEWORK_CMAKE_TOOLSET_THIRD_PARTY_JEMALLOC_BUILD_OPTIONS "--enable-debug")
  if("release" STREQUAL ${ATFRAMEWORK_CMAKE_TOOLSET_THIRD_PARTY_JEMALLOC_MODE})
    set(ATFRAMEWORK_CMAKE_TOOLSET_THIRD_PARTY_JEMALLOC_BUILD_OPTIONS "")
  endif()

  findconfigurepackage(
    PACKAGE
    Jemalloc
    BUILD_WITH_CONFIGURE
    CONFIGURE_FLAGS
    "--enable-static=no"
    "--enable-prof"
    "--enable-valgrind"
    "--enable-lazy-lock"
    "--enable-xmalloc"
    "--enable-mremap"
    "--enable-utrace"
    "--enable-munmap"
    ${ATFRAMEWORK_CMAKE_TOOLSET_THIRD_PARTY_JEMALLOC_BUILD_OPTIONS}
    INSTALL_TARGET
    "install_bin"
    "install_include"
    "install_lib"
    MAKE_FLAGS
    "-j4"
    PREBUILD_COMMAND
    "./autogen.sh"
    WORKING_DIRECTORY
    "${ATFRAMEWORK_CMAKE_TOOLSET_THIRD_PARTY_PACKAGE_DIR}"
    BUILD_DIRECTORY
    "${ATFRAMEWORK_CMAKE_TOOLSET_THIRD_PARTY_PACKAGE_DIR}/jemalloc-${ATFRAMEWORK_CMAKE_TOOLSET_THIRD_PARTY_JEMALLOC_PKG_VERSION}"
    PREFIX_DIRECTORY
    ${ATFRAMEWORK_CMAKE_TOOLSET_THIRD_PARTY_INSTALL_DIR}
    SRC_DIRECTORY_NAME
    "jemalloc-${ATFRAMEWORK_CMAKE_TOOLSET_THIRD_PARTY_JEMALLOC_PKG_VERSION}"
    GIT_BRANCH
    ${ATFRAMEWORK_CMAKE_TOOLSET_THIRD_PARTY_JEMALLOC_PKG_VERSION}
    GIT_URL
    "https://github.com/jemalloc/jemalloc.git")

  if(JEMALLOC_FOUND)
    echowithcolor(COLOR GREEN "-- Dependency: Jemalloc found.(${Jemalloc_LIBRARY_DIRS})")

    set(ATFRAMEWORK_CMAKE_TOOLSET_THIRD_PARTY_JEMALLOC_INC_DIR ${Jemalloc_INCLUDE_DIRS})
    set(ATFRAMEWORK_CMAKE_TOOLSET_THIRD_PARTY_JEMALLOC_LIB_DIR ${Jemalloc_LIBRARY_DIRS})

    list(APPEND ATFRAMEWORK_CMAKE_TOOLSET_THIRD_PARTY_PUBLIC_INCLUDE_DIRS
         ${ATFRAMEWORK_CMAKE_TOOLSET_THIRD_PARTY_JEMALLOC_INC_DIR})
  endif()
endif()
