include_guard(GLOBAL)

macro(PROJECT_THIRD_PARTY_RAPIDJSON_IMPORT)
  if(TARGET rapidjson)
    message(STATUS "Dependency(${PROJECT_NAME}): rapidjson using target: rapidjson")
    set(ATFRAMEWORK_CMAKE_TOOLSET_THIRD_PARTY_RAPIDJSON_LINK_NAME rapidjson)
  elseif(Rapidjson_INCLUDE_DIRS OR RapidJSON_INCLUDE_DIRS)
    if(Rapidjson_INCLUDE_DIRS AND NOT RapidJSON_INCLUDE_DIRS)
      set(RapidJSON_INCLUDE_DIRS ${Rapidjson_INCLUDE_DIRS})
      set(RapidJSON_FOUND ${Rapidjson_FOUND})
    endif()
    message(STATUS "Dependency(${PROJECT_NAME}): rapidjson using include directory: ${RapidJSON_INCLUDE_DIRS}")
    add_library(rapidjson INTERFACE IMPORTED)
    set_target_properties(rapidjson PROPERTIES INTERFACE_INCLUDE_DIRECTORIES ${RapidJSON_INCLUDE_DIRS})
    set(ATFRAMEWORK_CMAKE_TOOLSET_THIRD_PARTY_RAPIDJSON_LINK_NAME rapidjson)
  endif()
endmacro()

if(NOT TARGET rapidjson
   AND NOT Rapidjson_INCLUDE_DIRS
   AND NOT RapidJSON_INCLUDE_DIRS)
  # =========== third party rapidjson ==================
  if(NOT ATFRAMEWORK_CMAKE_TOOLSET_THIRD_PARTY_RAPIDJSON_VERSION)
    set(ATFRAMEWORK_CMAKE_TOOLSET_THIRD_PARTY_RAPIDJSON_VERSION "17aa824c928ea111e9b12a61e06d98335ce98f15") # 2021-05-07
  endif()
  if(NOT ATFRAMEWORK_CMAKE_TOOLSET_THIRD_PARTY_RAPIDJSON_GIT_URL)
    set(ATFRAMEWORK_CMAKE_TOOLSET_THIRD_PARTY_RAPIDJSON_GIT_URL "https://github.com/Tencent/rapidjson.git")
  endif()
  if(NOT ATFRAMEWORK_CMAKE_TOOLSET_THIRD_PARTY_RAPIDJSON_BUILD_DIR)
    project_third_party_get_build_dir(ATFRAMEWORK_CMAKE_TOOLSET_THIRD_PARTY_RAPIDJSON_BUILD_DIR "rapidjson"
                                      ${ATFRAMEWORK_CMAKE_TOOLSET_THIRD_PARTY_RAPIDJSON_VERSION})
  endif()

  if(NOT ATFRAMEWORK_CMAKE_TOOLSET_THIRD_PARTY_RAPIDJSON_BUILD_OPTIONS)
    set(ATFRAMEWORK_CMAKE_TOOLSET_THIRD_PARTY_RAPIDJSON_BUILD_OPTIONS
        "-DRAPIDJSON_BUILD_DOC=OFF" "-DRAPIDJSON_BUILD_EXAMPLES=OFF" "-DRAPIDJSON_BUILD_TESTS=OFF"
        "-DRAPIDJSON_BUILD_THIRDPARTY_GTEST=OFF")
  endif()
  set(ATFRAMEWORK_CMAKE_TOOLSET_THIRD_PARTY_RAPIDJSON_REPOSITORY_DIR
      "${PROJECT_THIRD_PARTY_PACKAGE_DIR}/rapidjson-${ATFRAMEWORK_CMAKE_TOOLSET_THIRD_PARTY_RAPIDJSON_VERSION}")

  find_configure_package(
    PACKAGE
    RapidJSON
    BUILD_WITH_CMAKE
    CMAKE_INHIRT_BUILD_ENV
    CMAKE_INHIRT_BUILD_ENV_DISABLE_C_FLAGS
    CMAKE_FLAGS
    ${ATFRAMEWORK_CMAKE_TOOLSET_THIRD_PARTY_RAPIDJSON_BUILD_OPTIONS}
    WORKING_DIRECTORY
    "${PROJECT_THIRD_PARTY_PACKAGE_DIR}"
    BUILD_DIRECTORY
    "${ATFRAMEWORK_CMAKE_TOOLSET_THIRD_PARTY_RAPIDJSON_BUILD_DIR}"
    PREFIX_DIRECTORY
    "${PROJECT_THIRD_PARTY_INSTALL_DIR}"
    SRC_DIRECTORY_NAME
    "rapidjson-${ATFRAMEWORK_CMAKE_TOOLSET_THIRD_PARTY_RAPIDJSON_VERSION}"
    GIT_BRANCH
    "${ATFRAMEWORK_CMAKE_TOOLSET_THIRD_PARTY_RAPIDJSON_VERSION}"
    GIT_URL
    "${ATFRAMEWORK_CMAKE_TOOLSET_THIRD_PARTY_RAPIDJSON_GIT_URL}")

  project_third_party_rapidjson_import()
  if(NOT RapidJSON_FOUND)
    echowithcolor(COLOR RED "-- Dependency(${PROJECT_NAME}): rapidjson is required")
    message(FATAL_ERROR "rapidjson not found")
  endif()
else()
  project_third_party_rapidjson_import()
endif()
