include_guard(GLOBAL)

if (NOT PROJECT_3RD_PARTY_PACKAGE_DIR)
  set (PROJECT_3RD_PARTY_PACKAGE_DIR "${PROJECT_SOURCE_DIR}/third_party/packages")
endif ()
if (NOT PROJECT_3RD_PARTY_INSTALL_DIR)
  set (PROJECT_3RD_PARTY_INSTALL_DIR "${PROJECT_SOURCE_DIR}/third_party/install/${PROJECT_PREBUILT_PLATFORM_NAME}")
endif ()

if (NOT EXISTS ${PROJECT_3RD_PARTY_PACKAGE_DIR})
  file(MAKE_DIRECTORY ${PROJECT_3RD_PARTY_PACKAGE_DIR})
endif ()

if (NOT EXISTS ${PROJECT_3RD_PARTY_INSTALL_DIR})
  file(MAKE_DIRECTORY ${PROJECT_3RD_PARTY_INSTALL_DIR})
endif ()