include_guard(DIRECTORY)

# =========== third party libsodium ==================
function(PROJECT_THIRD_PARTY_LIBSODIUM_IMPORT)
  if(TARGET sodium) # Official Findsodium.cmake
    message(STATUS "Dependency(${PROJECT_NAME}): Libsodium found target sodium")
    project_third_party_export_port_set(libsodium LINK_NAME sodium)
  elseif(TARGET unofficial-sodium::sodium) # vcpkg porting
    message(STATUS "Dependency(${PROJECT_NAME}): Libsodium found target unofficial-sodium::sodium")
    project_third_party_export_port_set(libsodium LINK_NAME unofficial-sodium::sodium)
  elseif(TARGET libsodium::libsodium) # Our porting
    message(STATUS "Dependency(${PROJECT_NAME}): Libsodium found target libsodium::libsodium")
    project_third_party_export_port_set(libsodium LINK_NAME libsodium::libsodium)
  endif()
  if(ATFRAMEWORK_CMAKE_TOOLSET_THIRD_PARTY_LIBSODIUM_LINK_NAME)
    project_build_tools_patch_default_imported_config(
      sodium unofficial-sodium::sodium unofficial-sodium::sodium_config_public libsodium::libsodium
      libsodium::libsodium_config_public)
  endif()
endfunction()

if(NOT TARGET sodium
   AND NOT TARGET unofficial-sodium::sodium
   AND NOT TARGET libsodium::libsodium)
  if(VCPKG_TOOLCHAIN)
    find_package(unofficial-sodium QUIET CONFIG)
    if(NOT TARGET unofficial-sodium::sodium)
      find_package(sodium QUIET)
    endif()
  else()
    find_package(sodium QUIET)
    if(NOT TARGET sodium)
      find_package(libsodium QUIET CONFIG)
      if(NOT TARGET unofficial-sodium::sodium AND NOT TARGET libsodium::libsodium)
        find_package(unofficial-sodium QUIET CONFIG)
      endif()
    endif()
  endif()
  if(TARGET sodium
     OR TARGET unofficial-sodium::sodium
     OR TARGET libsodium::libsodium)
    project_third_party_libsodium_import()
  endif()
endif()

# Build libsodium
if(NOT TARGET sodium
   AND NOT TARGET unofficial-sodium::sodium
   AND NOT TARGET libsodium::libsodium)
  project_third_party_port_declare(
    libsodium
    VERSION
    "1.0.21-RELEASE"
    GIT_URL
    "https://github.com/jedisct1/libsodium.git"
    BUILD_OPTIONS
    "-DCMAKE_POSITION_INDEPENDENT_CODE=ON"
    "-DBUILD_TESTING=OFF")

  project_third_party_try_patch_file(
    ATFRAMEWORK_CMAKE_TOOLSET_THIRD_PARTY_LIBSODIUM_PATCH_FILE "${CMAKE_CURRENT_LIST_DIR}" "libsodium"
    "${ATFRAMEWORK_CMAKE_TOOLSET_THIRD_PARTY_LIBSODIUM_VERSION}")

  set(ATFRAMEWORK_CMAKE_TOOLSET_THIRD_PARTY_LIBSODIUM_SOURCE_DIR
      "${PROJECT_THIRD_PARTY_PACKAGE_DIR}/${ATFRAMEWORK_CMAKE_TOOLSET_THIRD_PARTY_LIBSODIUM_SRC_DIRECTORY_NAME}")

  # libsodium does not ship a CMakeLists.txt. On MSVC we build native vcxproj via MSBuild; on Unix we use autotools.
  if(MSVC AND NOT MINGW)
    # ============ MSVC: MSBuild with vcxproj ============
    set(ATFRAMEWORK_CMAKE_TOOLSET_THIRD_PARTY_LIBSODIUM_MSBUILD_GIT_ARGS
        URL "${ATFRAMEWORK_CMAKE_TOOLSET_THIRD_PARTY_LIBSODIUM_GIT_URL}" REPO_DIRECTORY
        "${ATFRAMEWORK_CMAKE_TOOLSET_THIRD_PARTY_LIBSODIUM_SOURCE_DIR}" TAG
        "${ATFRAMEWORK_CMAKE_TOOLSET_THIRD_PARTY_LIBSODIUM_VERSION}")
    if(ATFRAMEWORK_CMAKE_TOOLSET_THIRD_PARTY_LIBSODIUM_PATCH_FILE
       AND EXISTS "${ATFRAMEWORK_CMAKE_TOOLSET_THIRD_PARTY_LIBSODIUM_PATCH_FILE}")
      list(APPEND ATFRAMEWORK_CMAKE_TOOLSET_THIRD_PARTY_LIBSODIUM_MSBUILD_GIT_ARGS PATCH_FILES
           "${ATFRAMEWORK_CMAKE_TOOLSET_THIRD_PARTY_LIBSODIUM_PATCH_FILE}")
    endif()
    project_git_clone_repository(${ATFRAMEWORK_CMAKE_TOOLSET_THIRD_PARTY_LIBSODIUM_MSBUILD_GIT_ARGS})
    unset(ATFRAMEWORK_CMAKE_TOOLSET_THIRD_PARTY_LIBSODIUM_MSBUILD_GIT_ARGS)

    if(EXISTS "${ATFRAMEWORK_CMAKE_TOOLSET_THIRD_PARTY_LIBSODIUM_SOURCE_DIR}")
      if(NOT EXISTS "${ATFRAMEWORK_CMAKE_TOOLSET_THIRD_PARTY_LIBSODIUM_BUILD_DIR}")
        file(MAKE_DIRECTORY "${ATFRAMEWORK_CMAKE_TOOLSET_THIRD_PARTY_LIBSODIUM_BUILD_DIR}")
      endif()

      # Determine linkage configuration
      if(ATFRAMEWORK_CMAKE_TOOLSET_THIRD_PARTY_LIBSODIUM_USE_SHARED OR BUILD_SHARED_LIBS)
        set(ATFRAMEWORK_CMAKE_TOOLSET_THIRD_PARTY_LIBSODIUM_MSBUILD_LINKAGE "DLL")
      else()
        set(ATFRAMEWORK_CMAKE_TOOLSET_THIRD_PARTY_LIBSODIUM_MSBUILD_LINKAGE "LIB")
      endif()

      # Determine platform
      if(CMAKE_SIZEOF_VOID_P EQUAL 8)
        set(ATFRAMEWORK_CMAKE_TOOLSET_THIRD_PARTY_LIBSODIUM_MSBUILD_PLATFORM "x64")
      else()
        set(ATFRAMEWORK_CMAKE_TOOLSET_THIRD_PARTY_LIBSODIUM_MSBUILD_PLATFORM "Win32")
      endif()
      if(CMAKE_GENERATOR_PLATFORM)
        string(TOUPPER "${CMAKE_GENERATOR_PLATFORM}" ATFRAMEWORK_CMAKE_TOOLSET_THIRD_PARTY_LIBSODIUM_GEN_PLATFORM_UC)
        if(ATFRAMEWORK_CMAKE_TOOLSET_THIRD_PARTY_LIBSODIUM_GEN_PLATFORM_UC STREQUAL "ARM64")
          set(ATFRAMEWORK_CMAKE_TOOLSET_THIRD_PARTY_LIBSODIUM_MSBUILD_PLATFORM "ARM64")
        elseif(ATFRAMEWORK_CMAKE_TOOLSET_THIRD_PARTY_LIBSODIUM_GEN_PLATFORM_UC STREQUAL "ARM")
          set(ATFRAMEWORK_CMAKE_TOOLSET_THIRD_PARTY_LIBSODIUM_MSBUILD_PLATFORM "ARM")
        endif()
        unset(ATFRAMEWORK_CMAKE_TOOLSET_THIRD_PARTY_LIBSODIUM_GEN_PLATFORM_UC)
      endif()

      # Select vcxproj path - prefer vs2022
      set(ATFRAMEWORK_CMAKE_TOOLSET_THIRD_PARTY_LIBSODIUM_VCXPROJ_SUBPATH
          "builds/msvc/vs2022/libsodium/libsodium.vcxproj")
      if(NOT
         EXISTS
         "${ATFRAMEWORK_CMAKE_TOOLSET_THIRD_PARTY_LIBSODIUM_SOURCE_DIR}/${ATFRAMEWORK_CMAKE_TOOLSET_THIRD_PARTY_LIBSODIUM_VCXPROJ_SUBPATH}"
      )
        set(ATFRAMEWORK_CMAKE_TOOLSET_THIRD_PARTY_LIBSODIUM_VCXPROJ_SUBPATH
            "builds/msvc/vs2019/libsodium/libsodium.vcxproj")
      endif()

      set(ATFRAMEWORK_CMAKE_TOOLSET_THIRD_PARTY_LIBSODIUM_MSBUILD_CONFIG
          "Release${ATFRAMEWORK_CMAKE_TOOLSET_THIRD_PARTY_LIBSODIUM_MSBUILD_LINKAGE}")

      # Generate version.h from version.h.in (libsodium requires this before build)
      set(ATFRAMEWORK_CMAKE_TOOLSET_THIRD_PARTY_LIBSODIUM_VERSION_H_IN
          "${ATFRAMEWORK_CMAKE_TOOLSET_THIRD_PARTY_LIBSODIUM_SOURCE_DIR}/src/libsodium/include/sodium/version.h.in")
      if(EXISTS "${ATFRAMEWORK_CMAKE_TOOLSET_THIRD_PARTY_LIBSODIUM_VERSION_H_IN}")
        file(READ "${ATFRAMEWORK_CMAKE_TOOLSET_THIRD_PARTY_LIBSODIUM_VERSION_H_IN}"
             ATFRAMEWORK_CMAKE_TOOLSET_THIRD_PARTY_LIBSODIUM_VERSION_H_CONTENT)
        # Extract version numbers from ATFRAMEWORK_CMAKE_TOOLSET_THIRD_PARTY_LIBSODIUM_VERSION e.g. "1.0.21-RELEASE" →
        # MAJOR=1, MINOR=0, PATCH=21
        string(REGEX MATCH "^([0-9]+)\\.([0-9]+)\\.([0-9]+)"
                     ATFRAMEWORK_CMAKE_TOOLSET_THIRD_PARTY_LIBSODIUM_VERSION_MATCH
                     "${ATFRAMEWORK_CMAKE_TOOLSET_THIRD_PARTY_LIBSODIUM_VERSION}")
        if(ATFRAMEWORK_CMAKE_TOOLSET_THIRD_PARTY_LIBSODIUM_VERSION_MATCH)
          set(ATFRAMEWORK_CMAKE_TOOLSET_THIRD_PARTY_LIBSODIUM_VER_MAJOR "${CMAKE_MATCH_1}")
          set(ATFRAMEWORK_CMAKE_TOOLSET_THIRD_PARTY_LIBSODIUM_VER_MINOR "${CMAKE_MATCH_2}")
          set(ATFRAMEWORK_CMAKE_TOOLSET_THIRD_PARTY_LIBSODIUM_VER_PATCH "${CMAKE_MATCH_3}")
        else()
          set(ATFRAMEWORK_CMAKE_TOOLSET_THIRD_PARTY_LIBSODIUM_VER_MAJOR "1")
          set(ATFRAMEWORK_CMAKE_TOOLSET_THIRD_PARTY_LIBSODIUM_VER_MINOR "0")
          set(ATFRAMEWORK_CMAKE_TOOLSET_THIRD_PARTY_LIBSODIUM_VER_PATCH "21")
        endif()

        # Extract SODIUM_LIBRARY_VERSION_MAJOR/MINOR from configure.ac
        set(ATFRAMEWORK_CMAKE_TOOLSET_THIRD_PARTY_LIBSODIUM_CONFIGURE_AC
            "${ATFRAMEWORK_CMAKE_TOOLSET_THIRD_PARTY_LIBSODIUM_SOURCE_DIR}/configure.ac")
        set(ATFRAMEWORK_CMAKE_TOOLSET_THIRD_PARTY_LIBSODIUM_LIB_VER_MAJOR "26")
        set(ATFRAMEWORK_CMAKE_TOOLSET_THIRD_PARTY_LIBSODIUM_LIB_VER_MINOR "3")
        if(EXISTS "${ATFRAMEWORK_CMAKE_TOOLSET_THIRD_PARTY_LIBSODIUM_CONFIGURE_AC}")
          file(READ "${ATFRAMEWORK_CMAKE_TOOLSET_THIRD_PARTY_LIBSODIUM_CONFIGURE_AC}"
               ATFRAMEWORK_CMAKE_TOOLSET_THIRD_PARTY_LIBSODIUM_CONFIGURE_AC_CONTENT)
          string(REGEX MATCH "SODIUM_LIBRARY_VERSION_MAJOR=([0-9]+)"
                       ATFRAMEWORK_CMAKE_TOOLSET_THIRD_PARTY_LIBSODIUM_LIB_VER_MAJOR_MATCH
                       "${ATFRAMEWORK_CMAKE_TOOLSET_THIRD_PARTY_LIBSODIUM_CONFIGURE_AC_CONTENT}")
          if(ATFRAMEWORK_CMAKE_TOOLSET_THIRD_PARTY_LIBSODIUM_LIB_VER_MAJOR_MATCH)
            set(ATFRAMEWORK_CMAKE_TOOLSET_THIRD_PARTY_LIBSODIUM_LIB_VER_MAJOR "${CMAKE_MATCH_1}")
          endif()
          string(REGEX MATCH "SODIUM_LIBRARY_VERSION_MINOR=([0-9]+)"
                       ATFRAMEWORK_CMAKE_TOOLSET_THIRD_PARTY_LIBSODIUM_LIB_VER_MINOR_MATCH
                       "${ATFRAMEWORK_CMAKE_TOOLSET_THIRD_PARTY_LIBSODIUM_CONFIGURE_AC_CONTENT}")
          if(ATFRAMEWORK_CMAKE_TOOLSET_THIRD_PARTY_LIBSODIUM_LIB_VER_MINOR_MATCH)
            set(ATFRAMEWORK_CMAKE_TOOLSET_THIRD_PARTY_LIBSODIUM_LIB_VER_MINOR "${CMAKE_MATCH_1}")
          endif()
          unset(ATFRAMEWORK_CMAKE_TOOLSET_THIRD_PARTY_LIBSODIUM_CONFIGURE_AC_CONTENT)
        endif()

        string(
          REPLACE
            "@VERSION@"
            "${ATFRAMEWORK_CMAKE_TOOLSET_THIRD_PARTY_LIBSODIUM_VER_MAJOR}.${ATFRAMEWORK_CMAKE_TOOLSET_THIRD_PARTY_LIBSODIUM_VER_MINOR}.${ATFRAMEWORK_CMAKE_TOOLSET_THIRD_PARTY_LIBSODIUM_VER_PATCH}"
            ATFRAMEWORK_CMAKE_TOOLSET_THIRD_PARTY_LIBSODIUM_VERSION_H_CONTENT
            "${ATFRAMEWORK_CMAKE_TOOLSET_THIRD_PARTY_LIBSODIUM_VERSION_H_CONTENT}")
        string(
          REPLACE "@SODIUM_LIBRARY_VERSION_MAJOR@" "${ATFRAMEWORK_CMAKE_TOOLSET_THIRD_PARTY_LIBSODIUM_LIB_VER_MAJOR}"
                  ATFRAMEWORK_CMAKE_TOOLSET_THIRD_PARTY_LIBSODIUM_VERSION_H_CONTENT
                  "${ATFRAMEWORK_CMAKE_TOOLSET_THIRD_PARTY_LIBSODIUM_VERSION_H_CONTENT}")
        string(
          REPLACE "@SODIUM_LIBRARY_VERSION_MINOR@" "${ATFRAMEWORK_CMAKE_TOOLSET_THIRD_PARTY_LIBSODIUM_LIB_VER_MINOR}"
                  ATFRAMEWORK_CMAKE_TOOLSET_THIRD_PARTY_LIBSODIUM_VERSION_H_CONTENT
                  "${ATFRAMEWORK_CMAKE_TOOLSET_THIRD_PARTY_LIBSODIUM_VERSION_H_CONTENT}")
        string(REPLACE "@SODIUM_LIBRARY_MINIMAL_DEF@" ""
                       ATFRAMEWORK_CMAKE_TOOLSET_THIRD_PARTY_LIBSODIUM_VERSION_H_CONTENT
                       "${ATFRAMEWORK_CMAKE_TOOLSET_THIRD_PARTY_LIBSODIUM_VERSION_H_CONTENT}")
        file(WRITE
             "${ATFRAMEWORK_CMAKE_TOOLSET_THIRD_PARTY_LIBSODIUM_SOURCE_DIR}/src/libsodium/include/sodium/version.h"
             "${ATFRAMEWORK_CMAKE_TOOLSET_THIRD_PARTY_LIBSODIUM_VERSION_H_CONTENT}")
        unset(ATFRAMEWORK_CMAKE_TOOLSET_THIRD_PARTY_LIBSODIUM_VERSION_H_CONTENT)
      endif()
      unset(ATFRAMEWORK_CMAKE_TOOLSET_THIRD_PARTY_LIBSODIUM_VERSION_H_IN)

      # Generate build script
      file(WRITE "${ATFRAMEWORK_CMAKE_TOOLSET_THIRD_PARTY_LIBSODIUM_BUILD_DIR}/run-build-release.ps1"
           "\$PSDefaultParameterValues['*:Encoding'] = 'UTF-8'${PROJECT_THIRD_PARTY_BUILDTOOLS_BASH_EOL}"
           "\$OutputEncoding = [System.Text.UTF8Encoding]::new()${PROJECT_THIRD_PARTY_BUILDTOOLS_BASH_EOL}")
      file(WRITE "${ATFRAMEWORK_CMAKE_TOOLSET_THIRD_PARTY_LIBSODIUM_BUILD_DIR}/run-build-release.bat"
           "@echo off${PROJECT_THIRD_PARTY_BUILDTOOLS_EOL}" "chcp 65001${PROJECT_THIRD_PARTY_BUILDTOOLS_EOL}")
      project_make_executable("${ATFRAMEWORK_CMAKE_TOOLSET_THIRD_PARTY_LIBSODIUM_BUILD_DIR}/run-build-release.ps1")
      project_make_executable("${ATFRAMEWORK_CMAKE_TOOLSET_THIRD_PARTY_LIBSODIUM_BUILD_DIR}/run-build-release.bat")

      # MSBuild command
      project_expand_list_for_command_line_to_file(
        BAT
        "${ATFRAMEWORK_CMAKE_TOOLSET_THIRD_PARTY_LIBSODIUM_BUILD_DIR}/run-build-release.bat"
        msbuild
        "${ATFRAMEWORK_CMAKE_TOOLSET_THIRD_PARTY_LIBSODIUM_SOURCE_DIR}/${ATFRAMEWORK_CMAKE_TOOLSET_THIRD_PARTY_LIBSODIUM_VCXPROJ_SUBPATH}"
        "/m"
        "/v:minimal"
        "/p:Configuration=${ATFRAMEWORK_CMAKE_TOOLSET_THIRD_PARTY_LIBSODIUM_MSBUILD_CONFIG}"
        "/p:Platform=${ATFRAMEWORK_CMAKE_TOOLSET_THIRD_PARTY_LIBSODIUM_MSBUILD_PLATFORM}")
      project_expand_list_for_command_line_to_file(
        PWSH
        "${ATFRAMEWORK_CMAKE_TOOLSET_THIRD_PARTY_LIBSODIUM_BUILD_DIR}/run-build-release.ps1"
        "&"
        msbuild
        "${ATFRAMEWORK_CMAKE_TOOLSET_THIRD_PARTY_LIBSODIUM_SOURCE_DIR}/${ATFRAMEWORK_CMAKE_TOOLSET_THIRD_PARTY_LIBSODIUM_VCXPROJ_SUBPATH}"
        "/m"
        "/v:minimal"
        "/p:Configuration=${ATFRAMEWORK_CMAKE_TOOLSET_THIRD_PARTY_LIBSODIUM_MSBUILD_CONFIG}"
        "/p:Platform=${ATFRAMEWORK_CMAKE_TOOLSET_THIRD_PARTY_LIBSODIUM_MSBUILD_PLATFORM}")

      # Run build
      if(ATFRAMEWORK_CMAKE_TOOLSET_PWSH)
        execute_process(
          COMMAND
            "${ATFRAMEWORK_CMAKE_TOOLSET_PWSH}" "-NoProfile" "-InputFormat" "None" "-ExecutionPolicy" "Bypass"
            "-NonInteractive" "-NoLogo" "-File"
            "${ATFRAMEWORK_CMAKE_TOOLSET_THIRD_PARTY_LIBSODIUM_BUILD_DIR}/run-build-release.ps1"
          WORKING_DIRECTORY "${ATFRAMEWORK_CMAKE_TOOLSET_THIRD_PARTY_LIBSODIUM_BUILD_DIR}"
                            ${ATFRAMEWORK_CMAKE_TOOLSET_EXECUTE_PROCESS_OUTPUT_OPTIONS}
          RESULT_VARIABLE ATFRAMEWORK_CMAKE_TOOLSET_THIRD_PARTY_LIBSODIUM_BUILD_RESULT)
      else()
        execute_process(
          COMMAND "${ATFRAMEWORK_CMAKE_TOOLSET_THIRD_PARTY_LIBSODIUM_BUILD_DIR}/run-build-release.bat"
          WORKING_DIRECTORY "${ATFRAMEWORK_CMAKE_TOOLSET_THIRD_PARTY_LIBSODIUM_BUILD_DIR}"
                            ${ATFRAMEWORK_CMAKE_TOOLSET_EXECUTE_PROCESS_OUTPUT_OPTIONS}
          RESULT_VARIABLE ATFRAMEWORK_CMAKE_TOOLSET_THIRD_PARTY_LIBSODIUM_BUILD_RESULT)
      endif()

      if(ATFRAMEWORK_CMAKE_TOOLSET_THIRD_PARTY_LIBSODIUM_BUILD_RESULT EQUAL 0)
        # Install headers
        file(INSTALL "${ATFRAMEWORK_CMAKE_TOOLSET_THIRD_PARTY_LIBSODIUM_SOURCE_DIR}/src/libsodium/include/sodium.h"
             DESTINATION "${PROJECT_THIRD_PARTY_INSTALL_DIR}/include")
        file(INSTALL "${ATFRAMEWORK_CMAKE_TOOLSET_THIRD_PARTY_LIBSODIUM_SOURCE_DIR}/src/libsodium/include/sodium"
             DESTINATION "${PROJECT_THIRD_PARTY_INSTALL_DIR}/include")
        # Install generated version.h
        if(NOT EXISTS "${PROJECT_THIRD_PARTY_INSTALL_DIR}/include/sodium/version.h")
          if(EXISTS
             "${ATFRAMEWORK_CMAKE_TOOLSET_THIRD_PARTY_LIBSODIUM_SOURCE_DIR}/src/libsodium/include/sodium/version.h")
            file(INSTALL
                 "${ATFRAMEWORK_CMAKE_TOOLSET_THIRD_PARTY_LIBSODIUM_SOURCE_DIR}/src/libsodium/include/sodium/version.h"
                 DESTINATION "${PROJECT_THIRD_PARTY_INSTALL_DIR}/include/sodium")
          endif()
        endif()
        # Remove build artifacts from include
        file(REMOVE "${PROJECT_THIRD_PARTY_INSTALL_DIR}/include/Makefile.am"
             "${PROJECT_THIRD_PARTY_INSTALL_DIR}/include/sodium/version.h.in")

        # Install libraries - MSBuild outputs to <source>/bin/<Platform>/<DebugOrRelease>/<PlatformToolset>/<DefaultLinkage>/
        # (see builds/msvc/properties/Output.props). Use GLOB_RECURSE under <source>/bin/ for robustness since
        # PlatformToolset comes from the vcxproj (e.g. v143) and DefaultLinkage is "static"/"dynamic" not "LIB"/"DLL".
        file(GLOB_RECURSE ATFRAMEWORK_CMAKE_TOOLSET_THIRD_PARTY_LIBSODIUM_INSTALL_LIBS
             "${ATFRAMEWORK_CMAKE_TOOLSET_THIRD_PARTY_LIBSODIUM_SOURCE_DIR}/bin/*.lib")
        file(GLOB_RECURSE ATFRAMEWORK_CMAKE_TOOLSET_THIRD_PARTY_LIBSODIUM_INSTALL_DLLS
             "${ATFRAMEWORK_CMAKE_TOOLSET_THIRD_PARTY_LIBSODIUM_SOURCE_DIR}/bin/*.dll")
        if(ATFRAMEWORK_CMAKE_TOOLSET_THIRD_PARTY_LIBSODIUM_INSTALL_LIBS)
          file(INSTALL ${ATFRAMEWORK_CMAKE_TOOLSET_THIRD_PARTY_LIBSODIUM_INSTALL_LIBS}
               DESTINATION "${PROJECT_THIRD_PARTY_INSTALL_DIR}/lib")
        endif()
        if(ATFRAMEWORK_CMAKE_TOOLSET_THIRD_PARTY_LIBSODIUM_INSTALL_DLLS)
          file(INSTALL ${ATFRAMEWORK_CMAKE_TOOLSET_THIRD_PARTY_LIBSODIUM_INSTALL_DLLS}
               DESTINATION "${PROJECT_THIRD_PARTY_INSTALL_DIR}/bin")
        endif()

        # For static builds, patch export.h
        if(ATFRAMEWORK_CMAKE_TOOLSET_THIRD_PARTY_LIBSODIUM_MSBUILD_LINKAGE STREQUAL "LIB")
          if(EXISTS "${PROJECT_THIRD_PARTY_INSTALL_DIR}/include/sodium/export.h")
            file(READ "${PROJECT_THIRD_PARTY_INSTALL_DIR}/include/sodium/export.h"
                 ATFRAMEWORK_CMAKE_TOOLSET_THIRD_PARTY_LIBSODIUM_EXPORT_H_CONTENT)
            string(REPLACE "#ifdef SODIUM_STATIC" "#if 1"
                           ATFRAMEWORK_CMAKE_TOOLSET_THIRD_PARTY_LIBSODIUM_EXPORT_H_CONTENT
                           "${ATFRAMEWORK_CMAKE_TOOLSET_THIRD_PARTY_LIBSODIUM_EXPORT_H_CONTENT}")
            file(WRITE "${PROJECT_THIRD_PARTY_INSTALL_DIR}/include/sodium/export.h"
                 "${ATFRAMEWORK_CMAKE_TOOLSET_THIRD_PARTY_LIBSODIUM_EXPORT_H_CONTENT}")
            unset(ATFRAMEWORK_CMAKE_TOOLSET_THIRD_PARTY_LIBSODIUM_EXPORT_H_CONTENT)
          endif()
        endif()

        # Create an imported target for find_package compatibility
        if(NOT TARGET libsodium::libsodium)
          add_library(libsodium::libsodium UNKNOWN IMPORTED)
          set_target_properties(libsodium::libsodium PROPERTIES INTERFACE_INCLUDE_DIRECTORIES
                                                                "${PROJECT_THIRD_PARTY_INSTALL_DIR}/include")
          # Find the installed .lib
          file(GLOB ATFRAMEWORK_CMAKE_TOOLSET_THIRD_PARTY_LIBSODIUM_LIB_FILE
               "${PROJECT_THIRD_PARTY_INSTALL_DIR}/lib/libsodium*.lib"
               "${PROJECT_THIRD_PARTY_INSTALL_DIR}/lib/sodium*.lib")
          if(ATFRAMEWORK_CMAKE_TOOLSET_THIRD_PARTY_LIBSODIUM_LIB_FILE)
            list(GET ATFRAMEWORK_CMAKE_TOOLSET_THIRD_PARTY_LIBSODIUM_LIB_FILE 0
                 ATFRAMEWORK_CMAKE_TOOLSET_THIRD_PARTY_LIBSODIUM_LIB_FILE_FIRST)
            set_target_properties(
              libsodium::libsodium PROPERTIES IMPORTED_LOCATION
                                              "${ATFRAMEWORK_CMAKE_TOOLSET_THIRD_PARTY_LIBSODIUM_LIB_FILE_FIRST}")
            unset(ATFRAMEWORK_CMAKE_TOOLSET_THIRD_PARTY_LIBSODIUM_LIB_FILE_FIRST)
          endif()
          unset(ATFRAMEWORK_CMAKE_TOOLSET_THIRD_PARTY_LIBSODIUM_LIB_FILE)
          if(ATFRAMEWORK_CMAKE_TOOLSET_THIRD_PARTY_LIBSODIUM_MSBUILD_LINKAGE STREQUAL "LIB")
            set_target_properties(libsodium::libsodium PROPERTIES INTERFACE_COMPILE_DEFINITIONS "SODIUM_STATIC=1")
          endif()
          set_target_properties(libsodium::libsodium PROPERTIES INTERFACE_LINK_LIBRARIES "advapi32")
        endif()
      else()
        message(WARNING "Dependency(${PROJECT_NAME}): libsodium MSBuild build failed")
      endif()

      unset(ATFRAMEWORK_CMAKE_TOOLSET_THIRD_PARTY_LIBSODIUM_MSBUILD_LINKAGE)
      unset(ATFRAMEWORK_CMAKE_TOOLSET_THIRD_PARTY_LIBSODIUM_MSBUILD_PLATFORM)
      unset(ATFRAMEWORK_CMAKE_TOOLSET_THIRD_PARTY_LIBSODIUM_MSBUILD_CONFIG)
      unset(ATFRAMEWORK_CMAKE_TOOLSET_THIRD_PARTY_LIBSODIUM_VCXPROJ_SUBPATH)
      unset(ATFRAMEWORK_CMAKE_TOOLSET_THIRD_PARTY_LIBSODIUM_BUILD_RESULT)
    endif()
  else()
    # ============ Unix/Linux/macOS/MinGW: autotools (configure + make) ============
    set(ATFRAMEWORK_CMAKE_TOOLSET_THIRD_PARTY_LIBSODIUM_CONFIGURE_OPTIONS)
    list(APPEND ATFRAMEWORK_CMAKE_TOOLSET_THIRD_PARTY_LIBSODIUM_CONFIGURE_OPTIONS "--disable-dependency-tracking")

    if(NOT MINGW)
      list(APPEND ATFRAMEWORK_CMAKE_TOOLSET_THIRD_PARTY_LIBSODIUM_CONFIGURE_OPTIONS "--disable-pie")
    endif()

    project_third_party_append_build_shared_lib_var(
      "libsodium" "" ATFRAMEWORK_CMAKE_TOOLSET_THIRD_PARTY_LIBSODIUM_BUILD_OPTIONS BUILD_SHARED_LIBS)

    if(ATFRAMEWORK_CMAKE_TOOLSET_THIRD_PARTY_LIBSODIUM_USE_SHARED OR BUILD_SHARED_LIBS)
      list(APPEND ATFRAMEWORK_CMAKE_TOOLSET_THIRD_PARTY_LIBSODIUM_CONFIGURE_OPTIONS "--enable-shared"
           "--disable-static")
    else()
      list(APPEND ATFRAMEWORK_CMAKE_TOOLSET_THIRD_PARTY_LIBSODIUM_CONFIGURE_OPTIONS "--disable-shared"
           "--enable-static")
    endif()

    if(ATFRAMEWORK_CMAKE_TOOLSET_THIRD_PARTY_LIBSODIUM_PATCH_FILE
       AND EXISTS "${ATFRAMEWORK_CMAKE_TOOLSET_THIRD_PARTY_LIBSODIUM_PATCH_FILE}")
      list(APPEND ATFRAMEWORK_CMAKE_TOOLSET_THIRD_PARTY_LIBSODIUM_BUILD_OPTIONS GIT_PATCH_FILES
           "${ATFRAMEWORK_CMAKE_TOOLSET_THIRD_PARTY_LIBSODIUM_PATCH_FILE}")
    endif()

    find_configure_package(
      PACKAGE
      libsodium
      BUILD_WITH_CONFIGURE
      AUTOGEN_CONFIGURE
      "bash"
      "./autogen.sh"
      CONFIGURE_FLAGS
      ${ATFRAMEWORK_CMAKE_TOOLSET_THIRD_PARTY_LIBSODIUM_CONFIGURE_OPTIONS}
      WORKING_DIRECTORY
      "${PROJECT_THIRD_PARTY_PACKAGE_DIR}"
      BUILD_DIRECTORY
      "${PROJECT_THIRD_PARTY_PACKAGE_DIR}/${ATFRAMEWORK_CMAKE_TOOLSET_THIRD_PARTY_LIBSODIUM_SRC_DIRECTORY_NAME}"
      PREFIX_DIRECTORY
      "${PROJECT_THIRD_PARTY_INSTALL_DIR}"
      SRC_DIRECTORY_NAME
      "${ATFRAMEWORK_CMAKE_TOOLSET_THIRD_PARTY_LIBSODIUM_SRC_DIRECTORY_NAME}"
      GIT_BRANCH
      "${ATFRAMEWORK_CMAKE_TOOLSET_THIRD_PARTY_LIBSODIUM_VERSION}"
      GIT_URL
      "${ATFRAMEWORK_CMAKE_TOOLSET_THIRD_PARTY_LIBSODIUM_GIT_URL}")

    # For static builds, patch export.h
    if(NOT ATFRAMEWORK_CMAKE_TOOLSET_THIRD_PARTY_LIBSODIUM_USE_SHARED AND NOT BUILD_SHARED_LIBS)
      if(EXISTS "${PROJECT_THIRD_PARTY_INSTALL_DIR}/include/sodium/export.h")
        file(READ "${PROJECT_THIRD_PARTY_INSTALL_DIR}/include/sodium/export.h"
             ATFRAMEWORK_CMAKE_TOOLSET_THIRD_PARTY_LIBSODIUM_EXPORT_H_CONTENT)
        string(REPLACE "#ifdef SODIUM_STATIC" "#if 1" ATFRAMEWORK_CMAKE_TOOLSET_THIRD_PARTY_LIBSODIUM_EXPORT_H_CONTENT
                       "${ATFRAMEWORK_CMAKE_TOOLSET_THIRD_PARTY_LIBSODIUM_EXPORT_H_CONTENT}")
        file(WRITE "${PROJECT_THIRD_PARTY_INSTALL_DIR}/include/sodium/export.h"
             "${ATFRAMEWORK_CMAKE_TOOLSET_THIRD_PARTY_LIBSODIUM_EXPORT_H_CONTENT}")
        unset(ATFRAMEWORK_CMAKE_TOOLSET_THIRD_PARTY_LIBSODIUM_EXPORT_H_CONTENT)
      endif()
    endif()

    unset(ATFRAMEWORK_CMAKE_TOOLSET_THIRD_PARTY_LIBSODIUM_CONFIGURE_OPTIONS)
  endif()

  # Try to find and import again after build
  if(NOT TARGET sodium
     AND NOT TARGET unofficial-sodium::sodium
     AND NOT TARGET libsodium::libsodium)
    find_package(sodium QUIET)
    if(NOT TARGET sodium)
      find_package(libsodium QUIET CONFIG)
    endif()
  endif()

  if(TARGET sodium
     OR TARGET unofficial-sodium::sodium
     OR TARGET libsodium::libsodium)
    project_third_party_libsodium_import()
  else()
    if(ATFRAMEWORK_CMAKE_TOOLSET_THIRD_PARTY_CI_MODE)
      project_build_tools_print_configure_log("${ATFRAMEWORK_CMAKE_TOOLSET_THIRD_PARTY_LIBSODIUM_BUILD_DIR}")
    endif()
  endif()

  unset(ATFRAMEWORK_CMAKE_TOOLSET_THIRD_PARTY_LIBSODIUM_SOURCE_DIR)
else()
  project_third_party_libsodium_import()
endif()
